# Generated by Django 4.1.3 on 2022-12-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='construido_por',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
